### ISSUE TITLE
How do I install 'torchsarchsorted'?

### ISSUE THREAD

**Issue by L33S3H** [krrish94/nerf-pytorch#39]
(nerf) C:\Users\user\Desktop\nerf-pytorch-master\nerf-pytorch-master>python train_nerf.py --config config/lego.yml
Traceback (most recent call last):
  File "train_nerf.py", line 13, in <module>
    from nerf import (CfgNode, get_embedding_function, get_ray_bundle, img2mse,
  File "C:\Users\user\Desktop\nerf-pytorch-master\nerf-pytorch-master\nerf\__init__.py", line 5, in <module>
    from .nerf_helpers import *
  File "C:\Users\user\Desktop\nerf-pytorch-master\nerf-pytorch-master\nerf\nerf_helpers.py", line 6, in <module>
    import torchsearchsorted
ModuleNotFoundError: No module named 'torchsearchsorted'

**Comment by krrish94** [comment]
`torchsearchsorted` is no longer needed if you are using newer pytorch versions (they have a `torch.searchsorted` implementation)

Perhaps this PR is a good starting point https://github.com/krrish94/nerf-pytorch/pull/19
